### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NingMeiWang** [fgblomqvist/steamworkshopdownloader#2]

**Comment by fgblomqvist** [comment]
I'll have to look into whether they perhaps killed the API version SWD relies on. There are some other good alternatives out there so I'm not sure if there is a point in still maintaining this, but I'll look into it and see if it just globally doesn't work anymore.

**Comment by NingMeiWang** [comment]
Thank you .
may be i am in China.



At 2020-03-23 20:34:30, "Fredrik Blomqvist" <notifications@github.com> wrote:

I'll have to look into whether they perhaps killed the API version SWD relies on. There are some other good alternatives out there so I'm not sure if there is a point in still maintaining this, but I'll look into it and see if it just globally doesn't work anymore.

**Comment by fgblomqvist** [comment]
Looked into it and yeah the API that SWD relies on has been more or less deprecated (ISteamRemoteStorage). It's still possible to download files for most games, but not as easily as before. I'd recommend you to instead use https://www.steamworkshopdownloader.io/ which supports the new method (although, it has to be proxied through their servers).

I will be archiving this project.

**Comment by NingMeiWang** [comment]
哇，谢谢了，这已经足够了。Thank you ,,



At 2020-03-28 00:17:53, "Fredrik Blomqvist" <notifications@github.com> wrote:

Looked into it and yeah the API that SWD relies on has been more or less deprecated (ISteamRemoteStorage). It's still possible to download files for most games, but not as easily as before. I'd recommend you to instead use https://www.steamworkshopdownloader.io/ which supports the new method (although, it has to be proxied through their servers).

I will be archiving this project.
